// src/About.tsx
function About() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-zinc-950 dark:to-neutral-950 transition-colors duration-300">
      <div className="max-w-4xl mx-auto px-4 py-16">
        <h1 className="text-5xl md:text-6xl font-bold mb-8 bg-gradient-to-r from-purple-700 via-purple-600 to-amber-600 dark:from-purple-400 dark:via-purple-300 dark:to-amber-400 bg-clip-text text-transparent" style={{ fontFamily: "'Anta', sans-serif" }}>
          About Me
        </h1>
        
        <div className="prose prose-lg dark:prose-invert max-w-none">
          <p className="text-gray-700 dark:text-gray-300 mb-6">
            Welcome to Igor Labworks - a creative space where technology meets art and design.
          </p>
          
          <p className="text-gray-700 dark:text-gray-300 mb-6">
            I'm Igor Petrik, a multidisciplinary maker passionate about exploring the intersection of:
          </p>
          
          <ul className="text-gray-700 dark:text-gray-300 space-y-2 mb-6">
            <li>Software Engineering & Development</li>
            <li>Electronics Design & Prototyping</li>
            <li>Automation & Systems</li>
            <li>Art & Design</li>
            <li>Interior Design & Architecture</li>
            <li>Home Improvement</li>
            <li>CAD & 3D Modeling</li>
            <li>Music Production & Audio DSP</li>
            <li>Light & Color Reproduction</li>
            <li>Burning Man Projects</li>
          </ul>
          
          <p className="text-gray-700 dark:text-gray-300">
            This portfolio showcases my journey through creative technology and artistic expression. 
            Stay tuned for projects, experiments, and adventures in making.
          </p>
        </div>
      </div>
    </div>
  )
}

export default About

// src/routes/about/+page.svelte
<svelte:head>
  <title>About · Igor Labworks</title>
  <meta
    name="description"
    content="Igor Petrik — a multidisciplinary maker exploring the intersection of technology, art, and design."
  />
</svelte:head>

<div class="relative min-h-screen overflow-hidden">
  <div
    class="pointer-events-none absolute right-10 top-20 h-96 w-96 rounded-full bg-purple-200/30 blur-3xl dark:bg-purple-800/20"
    style="transform: translateY({orbShift}px)"
  ></div>

  <div class="relative mx-auto max-w-4xl px-4 py-16">
    <h1
      in:fly={{ y: 30, duration: 800 }}
      class="font-display mb-8 bg-gradient-to-r from-purple-700 via-purple-600 to-amber-600 bg-clip-text text-5xl font-bold text-transparent dark:from-purple-400 dark:via-purple-300 dark:to-amber-400 md:text-6xl"
    >
      About Me
    </h1>

    <div class="prose prose-lg max-w-none dark:prose-invert">
      <p
        in:fly={{ x: -20, duration: 600, delay: 200 }}
        class="mb-6 text-gray-700 dark:text-gray-300"
      >
        Welcome to Igor Labworks — a creative space where technology meets art and
        design.
      </p>

      <p
        in:fly={{ x: -20, duration: 600, delay: 300 }}
        class="mb-6 text-gray-700 dark:text-gray-300"
      >
        I'm Igor Petrik, a multidisciplinary maker passionate about exploring the
        intersection of:
      </p>

      <ul class="mb-6 space-y-2 text-gray-700 dark:text-gray-300">
        {#each INTERESTS as interest, index (interest)}
          <li in:fly={{ x: -20, duration: 400, delay: 500 + index * 50 }}>
            {interest}
          </li>
        {/each}
      </ul>

      <p
        in:fly={{ x: -20, duration: 600, delay: 1000 }}
        class="text-gray-700 dark:text-gray-300"
      >
        This portfolio showcases my journey through creative technology and artistic
        expression. Stay tuned for projects, experiments, and adventures in making.
      </p>
    </div>
  </div>
</div>

<script lang="ts">
  import { fly } from "svelte/transition"
  import { scroll } from "$lib/stores/scroll.svelte"

  const INTERESTS = [
    "Software Engineering & Development",
    "Electronics Design & Prototyping",
    "Automation & Systems",
    "Art & Design",
    "Interior Design & Architecture",
    "Home Improvement",
    "CAD & 3D Modeling",
    "Music Production & Audio DSP",
    "Light & Color Reproduction",
    "Burning Man Projects",
  ]

  const orbShift = $derived(scroll.y * 0.15)
</script>
